export const providers = [
  ['ChatGPT', 'https://chatgpt.com/', 'Regular, project, custom GPT chats and Dots', '普通聊天、项目、自定义 GPT 和 Dots', 'chatgpt-light.svg', 'chatgpt-dark.svg'],
  ['Claude', 'https://claude.ai/', 'Saved chats, including project chats', '已保存的聊天，包括项目内的聊天', 'claude.svg'],
  ['DeepSeek', 'https://chat.deepseek.com/', 'Saved chats', '已保存的聊天', 'deepseek.svg'],
  ['Gemini', 'https://gemini.google.com/', 'Saved chats', '已保存的聊天', 'gemini.webp'],
  ['Grok', 'https://grok.com/', 'Saved chats', '已保存的聊天', 'grok.svg'],
  ['Perplexity', 'https://www.perplexity.ai/', 'Saved search conversations', '已保存的搜索对话', 'perplexity.svg'],
  ['Qwen', 'https://chat.qwen.ai/', 'Saved chats, including project chats', '已保存的聊天，包括项目内的聊天', 'qwen.png'],
  ['Qianwen', 'https://www.qianwen.com/', 'Saved chats', '已保存的聊天', 'qianwen-light.png', 'qianwen-dark.png'],
];

export const copy = {
  en: {
    title: 'ChatPick — Find your way through AI chats',
    description: 'Navigate AI chats by question and answer section. Export conversations as Markdown or PDF.',
    skip: 'Skip to content', nav: ['Features', 'Supported chats', 'Privacy'], language: '中文',
    headline: ['Find your way', 'through AI chats.'],
    intro: 'Jump to an earlier question, find a section in its answer, or save the conversation as Markdown or PDF.',
    storeAdd: 'Add to', storeChoose: 'Choose your browser.',
    featuresTitle: 'Features',
    features: [
      ['Find an earlier question', 'Choose a question from the directory to return to that part of the conversation. Even repeated questions have their own place.', '01-questions.webp', 'ChatPick question directory beside an example conversation'],
      ['Go straight to an answer section', 'Open a question’s answer headings, then select the section you want to read. Long replies become easier to revisit.', '02-answer-sections.webp', 'ChatPick answer section menu beside the question directory'],
      ['Save as Markdown or PDF', 'Download a conversation to read, search or keep in your notes. If some content is missing, ChatPick tells you before downloading.', '04-export.webp', 'ChatPick Markdown and PDF export menu'],
      ['Match your chat’s appearance', 'Follow the website’s colors, choose a light or dark appearance, and use English or Chinese. You can turn ChatPick off for any supported website.', '03-site-colors.webp', 'ChatPick navigation on a dark example chat page'],
    ],
    sitesTitle: 'Works with your AI chats',
    themeLight: 'Switch to light appearance', themeDark: 'Switch to dark appearance',
    privacyHeading: 'Privacy', privacyTitle: 'Your chats stay in your browser.',
    privacyIntro: 'ChatPick uses your existing sign-in to read the current conversation. Your chat content is never sent to the developer.',
    privacyPoints: ['No analytics or advertising', 'Only preferences are saved', 'Exports are generated locally'], privacyLink: 'Read the privacy policy',
    faqTitle: 'Frequently asked questions', faq: [
      ['Does it work on every page?', 'ChatPick appears on supported saved conversation pages. It stays out of home pages, settings, project overviews and shared links. Sign in to your chat provider as usual.'],
      ['Can I turn it off for a website?', 'Yes. Each supported website has its own enable switch, and all are enabled by default. Turning it off restores any native navigation ChatPick had replaced.'],
      ['Will every answer have a section menu?', 'Only answers with headings have a section menu. Questions are still available in the directory.'],
      ['What is included in an export?', 'Text is saved as Markdown or PDF. Images and attachments are represented by text notices. If history is unavailable or a reply is still generating, the export is marked as partial.'],
    ],
    closing: 'Get ChatPick',
    footer: 'Question navigation for AI conversations.', footerPrivacy: 'Privacy policy', footerContact: 'Contact', independent: 'An independent project, not affiliated with the supported AI providers.',
    policyBack: 'Back to ChatPick',
  },
  'zh-CN': {
    title: 'ChatPick — 让 AI 长对话更好找',
    description: '按问题和回答章节快速跳转 AI 对话，支持 Markdown 和 PDF 导出。',
    skip: '跳到正文', nav: ['功能', '支持的网站', '隐私'], language: 'English',
    headline: ['让 AI 长对话', '更好找。'],
    intro: '跳回之前的提问，找到回答中的某个章节，或将整段对话保存为 Markdown 和 PDF。',
    storeAdd: '添加到', storeChoose: '选择你的浏览器。',
    featuresTitle: '功能',
    features: [
      ['找到之前的问题', '从目录中选择一个问题，直接回到那段对话。相同的提问出现多次，也能分别找到。', '01-questions.webp', '示例对话旁的 ChatPick 问题目录'],
      ['直达回答中的章节', '展开一个问题的回答标题，再选择想看的章节。长回答也能快速回到需要的内容。', '02-answer-sections.webp', '问题目录旁展开的 ChatPick 回答章节菜单'],
      ['保存为 Markdown 或 PDF', '下载对话，方便阅读、搜索或整理到笔记中。内容不完整时，ChatPick 会在下载前明确提示。', '04-export.webp', 'ChatPick 的 Markdown 和 PDF 导出菜单'],
      ['跟随聊天网页的外观', '跟随网站配色，选择浅色或深色外观，使用英文或中文。也可以为任意支持的网站单独关闭 ChatPick。', '03-site-colors.webp', '深色示例聊天页面中的 ChatPick 导航'],
    ],
    sitesTitle: '支持你常用的 AI 聊天',
    themeLight: '切换到浅色外观', themeDark: '切换到深色外观',
    privacyHeading: '隐私', privacyTitle: '聊天内容留在你的浏览器里。',
    privacyIntro: 'ChatPick 使用已有登录状态读取当前对话。聊天内容不会发送给开发者。',
    privacyPoints: ['没有分析统计或广告', '仅保存偏好设置', '在本机生成导出文件'], privacyLink: '阅读隐私政策',
    faqTitle: '常见问题', faq: [
      ['所有页面都能用吗？', 'ChatPick 只在支持的已保存对话页面显示。首页、设置、项目概览和分享页面不显示导航。像平时一样登录对应 AI 平台即可。'],
      ['可以单独关闭某个网站吗？', '可以。每个支持的网站都有独立启用开关，默认开启。关闭后，如果 ChatPick 替换了网站的原生导航，也会恢复原来的导航。'],
      ['每个回答都有章节目录吗？', '有标题的回答才会显示章节目录。没有标题时，仍然可以通过问题目录跳转。'],
      ['导出会包含哪些内容？', '文字可以保存为 Markdown 或 PDF，图片和附件以文字说明保留。历史不可用或回答仍在生成时，导出会标记为部分内容。'],
    ],
    closing: '获取 ChatPick',
    footer: 'AI 对话的问题导航。', footerPrivacy: '隐私政策', footerContact: '联系', independent: '独立项目，与所支持的 AI 平台没有隶属关系。',
    policyBack: '返回 ChatPick',
  },
};
